[package]
name = "parkeerservice"
version = "0.1.0"
edition = "2024"

[features]
default = []
python-bindings = [
    "dep:tokio",
    "dep:pyo3",
    "dep:pyo3-async-runtimes",
    "dep:pyo3-log",
]

[dependencies]
chrono = { version = ">=0.4, < 0.5", features = ["serde"] }
log = ">=0.4.0"
regex = ">=1.12.0, < 1.13"
reqwest = { version = ">=0.12.0, < 0.13", default-features = false, features = [
    "default-tls",
    "json",
    "cookies",
] }
serde_json = ">=1, < 1.1"
thiserror = ">=2, < 2.1"
urlencoding = ">=2.1, < 2.2"
tokio = { version = "1", features = ["full"], optional = true }
pyo3 = { version = ">=0.24.0", features = [
    "experimental-async",
    "chrono",
    "experimental-inspect",
], optional = true }
pyo3-async-runtimes = { version = "0.27", features = [
    "attributes",
    "tokio-runtime",
], optional = true }
pyo3-log = { version = ">=0.13, <0.14", optional = true }
